GET http://localhost:8000/api/products/ HTTP/1.1

###

POST localhost:8000/api/products/ HTTP/1.1
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2NTUxMjUwLCJpYXQiOjE3NDY1NTA5NTAsImp0aSI6ImJlNmExYzE0MzBkMjQ1NjM4NTNkZjkzZGEzNTY5MTUzIiwidXNlcl9pZCI6MX0.4BYypgOUzbEEm3LE-NX9NVC742NcDowR3ELpeJvuSko

{
  "name" : "TV1",
  "price": "300.00",
  "stock": 14,
  "description": "Amazing TV"
}

###

POST localhost:8000/auth/sign-in/ HTTP/1.1
Content-Type: application/json

{
  "username": "admin2",
  "password": "admin2"
}

###
GET localhost:8000/api/products/1/ HTTP/1.1
#Content-Type: application/json
#Authorization: Bearer

###
PUT localhost:8000/api/products/1/ HTTP/1.1
Content-Type: application/json

{
  "name" : "TV1",
  "price": "300.00",
  "stock": 14,
  "description": "Amazing TV"
}

###
GET localhost:8000/api/orders/ HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzQ2ODIyNTc5LCJpYXQiOjE3NDY4MjIyNzksImp0aSI6IjQxNmIyMDliNWUwODRkNTY5ZGVkMWI2Y2FiMTkyM2VmIiwidXNlcl9pZCI6Mn0.uJmqaOVLCcYu1f5cmfIGUgxi_dJFZQwDmU-kZww2yIA