GET http://localhost:8000/api/products/ HTTP/1.1

###

POST localhost:8000/api/products/ HTTP/1.1
Content-Type: application/json

{
  "name" : "TV1",
  "price": "300.00",
  "stock": 14,
  "description": "Amazing TV"
}