# Generated by Django 5.2 on 2025-04-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newmodel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newmodel',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
